name: tinder_clone
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.8.1 <3.0.0"
  flutter: 1.22.3
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # state management
  state_notifier: 0.6.0
  hooks_riverpod: 0.12.1
  flutter_hooks: 0.15.0
  subscription_holder: 2.0.0+3
  rxdart: 0.24.1
  # ui
  animations: 1.1.2
  gap: 1.2.0
  mono_kit: 0.17.2+1
  adaptive_dialog: 0.9.0+1
  font_awesome_flutter: 8.10.0

  # Firebase
  firebase_core: 0.5.2
  firestore_ref: 0.9.2
  firebase_auth: 0.18.3
  cloud_firestore: 0.14.3
  firebase_analytics: 6.2.0
  #  firebase_messaging: 0.0.0
  #  firebase_storage: 0.0.0
  freezed_annotation: 0.12.0
  functional_widget_annotation: 0.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  functional_widget: 0.8.0
  build_runner: 1.10.2
  freezed: 0.12.2
  json_serializable: 3.5.0
  pedantic_mono: 1.10.0+3
  intl_translation: 0.17.10+1
flutter:
  uses-material-design: true
